### PR TITLE
Get remaining unit tests passing when new backend code is enabled

### PR DESCRIPTION
**Pull request by dae**
@david-allison had done the vast majority of the work here already, and there were only 6 tests failing. With the exception of the exception mapping, these all turned out to be problems with the tests rather than the library code, and "fixing" here mainly involved disabling them after figuring out why they were failing.

The synchronous change was not required for the tests, and was just something I noticed while working through the code.

Tested by manually enabling the new code path:

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
index fcb25ce71..aff48859f 100644
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java
@@ -87,7 +87,7 @@ public class AnkiDroidApp extends Application {
      *
      * Set this and {@link com.ichi2.libanki.Consts#SCHEMA_VERSION} to 16.
      */
-    public static boolean TESTING_USE_V16_BACKEND = false;
+    public static boolean TESTING_USE_V16_BACKEND = true;
 
     public static final String XML_CUSTOM_NAMESPACE = "http://arbitrary.app.namespace/com.ichi2.anki";
 
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
index 495b5ec00..b79144952 100644
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/Consts.kt
@@ -106,7 +106,7 @@ object Consts {
 
     // deck schema & syncing vars
     @JvmField
-    var SCHEMA_VERSION = 11
+    var SCHEMA_VERSION = 16
 
     /** The database schema version that we can downgrade from  */
     const val SCHEMA_DOWNGRADE_SUPPORTED_VERSION = 16
```

### CODE REVIEW

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java [hunk 1]
```diff
@@ -176,14 +177,20 @@ private void selectNewDeck() {
 
     @Test
     public void ensureDeckTree() {
+        if (AnkiDroidApp.TESTING_USE_V16_BACKEND) {
+            // assertEquals() fails with the new backend, because the ids don't match.
+            // While it could be updated to work with the new backend, it would be easier
+            // to switch to the backend's tree calculation in the future, which is tested
```
Comment (mikehardy) [inline AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java:183]: Seems fair - is this something we should peel off to a separate tracking issue? There are enough of us in the codebase with enough competing priorities I fear it will be lost otherwise? Or perhaps a RustCleanup annotation

File: AnkiDroid/src/main/java/com/ichi2/libanki/DB.java [hunk 2]
```diff
@@ -78,8 +78,12 @@ public DB(@NonNull String ankiFilename, @Nullable OpenHelperFactory openHelperFa
         SupportSQLiteOpenHelper helper = getSqliteOpenHelperFactory(openHelperFactory).create(configuration);
         // Note: This line creates the database and schema when executed using a Rust backend
         mDatabase = new DatabaseChangeDecorator(helper.getWritableDatabase());
+        // No-op except when using the old Java backend
         mDatabase.disableWriteAheadLogging();
-        mDatabase.query("PRAGMA synchronous = 2", null);
+        if (!AnkiDroidApp.TESTING_USE_V16_BACKEND) {
+            // full sync is not required when using a WAL
+            mDatabase.query("PRAGMA synchronous = 2", null);
```
Comment (mikehardy) [inline AnkiDroid/src/main/java/com/ichi2/libanki/DB.java:91]: excellent - doc snippet is conclusive thanks for including that

**Review by mikehardy — APPROVED** [review]
These all look fine to me, my only comment is a possibility of a RustCleanup annotation on first commit. I'd love for David to have a look but it all looks great, and that's not a blocker for me

Now I just fear what you'll see if you head over to Anki-Android-Backend, my first efforts in that repo have been just to update dependencies to more or less current but I'm only part way there and I fear it's a bit un-hygienic at the moment

Either way, rare treat to see a PR from you here, very much appreciated

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java (hunk 1 above)
Comment (dae) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java:183]: My thinking there was the comment will serve as a reminder when it comes time to remove TESTING_USE_V16_BACKEND, but I can add a RustCleanup if you think it best (or feel free to just push changes into this PR)

**Comment by dae** [comment]
> Now I just fear what you'll see if you head over to Anki-Android-Backend, my first efforts in that repo have been just to update dependencies to more or less current but I'm only part way there and I fear it's a bit un-hygienic at the moment

I wouldn't worry too much about it at the moment - if the old deps are pinned properly they should suffice until AnkiDroid has been updated to work with the 2.1.34 schema 16 code. Once that's done and there's no longer a need to support running with the v11 schema, updating to newer backend releases should be simpler (at least after the initial hurdle of moving from 2.1.34->latest; there were a number of infrastructure changes in the interim which have since settled down).

File: AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java:183]: given use of a constant that will disappear, comment does seem adequate

**Comment by mikehardy** [comment]
Hey @dae - had a problem with this one

Learnt today David will have really limited availability for a while

I pulled this locally and ran it through our typical CI battery without the changes described above; all passed so it will work for non-V16 testers

I made the changes mentioned above and got this, do you see this?

``06-11 15:29:25.065 17469 17469 E AndroidRuntime: FATAL EXCEPTION: main
06-11 15:29:25.065 17469 17469 E AndroidRuntime: Process: com.ichi2.anki, PID: 17469
06-11 15:29:25.065 17469 17469 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method shouldDiscardUnknownFields()Z in class Lcom/google/protobuf/CodedInputStream; or its super classes (declaration of 'com.google.protobuf.CodedInputStream' appears in /data/app/~~S5licqjOJ2ZPjnEY18oZhw==/com.ichi2.anki.tests-UifBqUSW95g7VOtg5JzcJw==/base.apk)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:317)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at BackendProto.Backend$Json.<init>(Backend.java:3577)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at BackendProto.Backend$Json.<init>(Backend.java:3528)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at BackendProto.Backend$Json$1.parsePartialFrom(Backend.java:3980)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at BackendProto.Backend$Json$1.parsePartialFrom(Backend.java:3974)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:173)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at BackendProto.Backend$Json.parseFrom(Backend.java:3706)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at net.ankiweb.rsdroid.RustBackendImpl.getConfigJson(RustBackendImpl.java:1332)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at net.ankiweb.rsdroid.BackendMutex.getConfigJson(BackendMutex.java:907)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.backend.RustConfigBackend.get_string(RustConfigBackend.kt:42)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.backend.RustConfigBackend.not_has_or_is_null(RustConfigBackend.kt:83)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.ConfigV16.isNull(ConfigV16.kt:28)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.Collection.get_config(Collection.kt:2374)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.sched.SchedV2._rolloverHour(SchedV2.java:2246)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.sched.SchedV2._timingToday(SchedV2.java:2265)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.sched.SchedV2._updateCutoff(SchedV2.java:2186)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.sched.SchedV2.<init>(SchedV2.java:166)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.Collection._loadScheduler(Collection.kt:221)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.Collection.<init>(Collection.kt:164)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.CollectionV16.<init>(CollectionV16.kt:33)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.backend.RustDroidV16Backend.createCollection(RustDroidV16Backend.kt:44)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.Storage.Collection(Storage.java:109)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.libanki.Storage.Collection(Storage.java:86)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.anki.CollectionHelper.openCollection(CollectionHelper.java:126)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:149)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.anki.services.BootService.getColSafe(BootService.kt:67)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.anki.services.BootService.onReceive(BootService.kt:30)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:228)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
06-11 15:29:25.065 17469 17469 E AndroidRuntime: 	at androidx.test.runner.MonitoringInstrumentation.callApplicationOnCreate(MonitoringInstrumentation.java:442)
`

```

Are you referencing a local build of Anki-Android-Backend for this, with something extra done (perhaps using a newer anki submodule ref?)
I've noticed that the collection is upgraded to V16 on disk so after this you can't run V11 code against it seemingly. My test started with a V11 collection on emulator disk from the non-V16 test run, it wasn't a clean run from that perspective, perhaps that affected it?

**Comment by mikehardy** [comment]
I note that Anki-Android-Backend has this:

>         protobufVersion = "3.19.3"

While Anki-Android has this:

>     implementation 'com.google.protobuf:protobuf-java:3.21.1' // This is required when loading from a file

However, those aspects were not perturbed in the PR and non-V16 appears to work. The related method (according to github threads in related repos) indicate method was implemented in 3.17.1 so this is unexpected.

**Comment by dae** [comment]
The changes in this PR don't touch any protobuf-related code, so presumably you'd get the same failures if you switched to V16 on ankidroid main? I wrote these before looking into making changes to the backend, so I would have been using the standard release build from David in build.gradle. I've only done testing inside AndroidStudio on a sim; were you testing on a device? Some Googling of that error seems to point to it perhaps being connected to ProGuard? https://github.com/protocolbuffers/protobuf/issues/8956

**Comment by mikehardy** [comment]
Yeah seems to work if you are V11 only, but once you touch a collection with V16, then it goes sideways every time. If you rm-rf /sdcard/AnkiDroid and go back to V11 it works.


It seems like a multi-bug:

1- there's an unknown protobuf field, which is likely a problem
2- protobuf blows up for some reason (proguard removing something? something else?) if it sees an unknown field

1 can likely be tackled separately by instrumenting the last stack frame under our control and dumping the protobuf fields and looking for unexpected things?

2 I dunno, the internet was slim pickings on information on this one. Elimination of proguard as a cause can be done by turning off minification everywhere and re-trying at least

**Comment by dae** [comment]
Sounds like it may an existing bug on main? I'll try reproduce it when I have a chance.

**Comment by dae** [comment]
When I try to load a V16 collection with stock AnkiDroid, it fails due to the previously-mentioned /tmp issue. If I apply the fix covered in https://github.com/ankidroid/Anki-Android/pull/11600 to the top of getInstance() in DroidBackendFactory, the downgrade succeeds and I'm able to navigate in the app.

**Review by david-allison — APPROVED** [review]
Thanks so much for this & for the code contributions in general! 

I'm both overcommitted in terms of obligations (until August), and a family member is terminally ill, so I'm not going to be regularly available.

I /really/ don't want to be a blocker for things here, please don't block things on me. Worst case is I'll catch up later

**Comment by dae** [comment]
Really sorry to hear about the family member David. :-(

**Comment by dae** [comment]
Closing in favor of #11644

**Comment by mikehardy** [comment]
I captured the comment about a need for a more specific error message in a separate issue and flagged it up for any interested person to work on. I think that harvests all the discussion here
