### PR TITLE
fix: CORS issue with JS loading

### LINKED ISSUE #16352: [BUG]: Externally loaded JavaScript doesn't seem to work anymore in 2.18
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Using `import '<path to file in collection.media>';` in a card's script tag doesn't seem to work anymore, either through a relative path or by using the 'https://appassets.androidplatform.net' prefix.

### Expected behaviour

The file is imported correctly as in the desktop version or at least can be imported through the prefix mentioned above.

### Actual behaviour

The file fails to be imported. Looking through the debugger, it complains that `file://` is not a valid protocol in CORS when using a relative path and it says the file wasn't found when using the appassets URL.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(10)

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g(10) Build/RRBS31.Q1-3-48-22; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.26 Mobile Safari/537.36

ACRA UUID = 259a6cb7-7280-4007-8d07-39acff87e836

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This used to work in the previous version (2.17). I might be wrong, but I think it may have been inadvertently added in [this](https://github.com/ankidroid/Anki-Android/commit/e55cae28afc9ffcd9583a93e0f890ecb3351eca4) commit.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #16373: [BUG]: Fetch API cannot load, URL scheme "file" is not supported.
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I use interactive buttons inside my card, And I have button to access to _collection.html from media folder and grab content from there, It was working perfectly, until I updated Ankidroid to 2.18 (as I think, but I don't remember the exact version, about 2 months ago it was working with the latest version), when I tried to remote debug, it shows this:

```
Fetch API cannot load file:///storage/emulated/0/AnkiDroid/collection.media/_collection.html. URL scheme "file" is not supported.
searchAndShowPopup @ _script.js:93
(anonymous) @ _script.js:62
_script.js:105  Error fetching collection: TypeError: Failed to fetch
    at searchAndShowPopup (_script.js:93:9)
    at HTMLSpanElement.<anonymous> (_script.js:62:11)
```

Is there any solutions ? I need interactive cards.
NOTE: it is working perfectly on Anki desktop 24 (latest version as of today)

### Expected behaviour

be able to access _collection.html file without any errors

### Actual behaviour

fails to access the file.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2101K6G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2101K6G Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = b8213169-64ed-473b-b9ac-bf2dafbccea7

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #16352
* Fixes #16373

## Approach
Add `Access-Control-Allow-Origin = *`, like 2.15.6 had

## How Has This Been Tested?

Emulator 34:
With the deck provided at https://github.com/ankidroid/Anki-Android/issues/16352#issuecomment-2094254299.

If everything is alright, `Testing` is added to the front side.

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

File: AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            return null
+        }
+        try {
+            val file = url.toFile()
+            if (file.parent != mediaDir || !file.exists()) {
+                return null
+            }
+            val inputStream = FileInputStream(file)
+            return WebResourceResponse(guessMimeType(file.path), null, inputStream).apply {
+                responseHeaders = mapOf("Access-Control-Allow-Origin" to "*")
```
Comment (david-allison) [inline AnkiDroid/src/main/java/com/ichi2/anki/ViewerResourceHandler.kt:47]: As discussed previously, we should aim to do better here.

But since we haven't formally moved away from the architecture where our collection/media was world-writable. Fine for now

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
@BrayanDSO any reason this was closed?

**Comment by BrayanDSO** [comment]
Deleted the branch by mistake

**Review by mikehardy — APPROVED** [review]
LGTM, thank you!
