### PR TITLE
Convert import/export zip file usage to library: commons-compress - Allows >2GB imports

### LINKED ISSUE #6419: "This isn't a valid apkg file" when importing files over 2GB
User-reported. We're not providing error reporting on many paths which involve the string: `R.string.import_log_no_apkg`.

Many of these errors could be caused by errors other than a bad file import. 

User had appropriate space for a large (2.4GB) file, and 4GB RAM. Stated that it imported correctly on PC. This implies we may have a bug here, but there's no opportunity to trace.

File: AnKing Step 1 V7 with Media.apkg: https://mega.nz/folder/UAwVRQbb#dA6sMOtPjRgqI83FYNvTug

### PR DESCRIPTION
**Pull request by david-allison-1**
## Query

Since this is a library change, I wouldn't feel totally comfortable in putting this in a point release. Not sure how this works with semver.

## Goals

* Check the constructor to ensure that there's no nastiness in the change.

## Purpose / Description

Allows import of apkg >2GB.

`new java.util.zip.ZipFile()` failed with:

`java.util.zip.ZipException: error in opening zip file`

This was also performed in the export side to keep library use consistent

Sadly, syncing uses `ZipFile.OPEN_READ | ZipFile.OPEN_DELETE`, and there does not seem to be a direct replacement in the library so I've kept this as using `java.util.zip` for now.

## Fixes
Fixes #6419

## Approach
Switch to commons-compress for import/export of apkg/colpkg files.

## How Has This Been Tested?

Tested on an API 27 emulator, which failed, and now handles a 2.4GB file

Tested on my device (Android 9) via in import/export cycle of a known good profile

Currently testing on an API 16 emulator

* TBC - timing details

## Learning

Apparently reported in 2007... https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6599383

https://stackoverflow.com/questions/53186835/error-in-opening-zip-file-opening-of-big-zip-files-2gb

https://commons.apache.org/proper/commons-compress/

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Aware of the test failure - performing another run locally, and will force push when it passes.

**Comment by david-allison-1** [comment]
Looks like this is a no-go. Fails on `API < 27`

```
com.ichi2.anki.tests.libanki.ImportTest > testAnki2DiffmodelTemplates[test(AVD) - 4.1.2] FAILED 
	java.lang.NoSuchMethodError: java.io.File.toPath
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:256)
com.ichi2.anki.tests.libanki.ImportTest > testAnki2Updates[test(AVD) - 4.1.2] FAILED 
	java.lang.NoSuchMethodError: java.io.File.toPath
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:256)
com.ichi2.anki.tests.libanki.ImportTest > testApkg[test(AVD) - 4.1.2] FAILED 
	java.lang.NoSuchMethodError: java.io.File.toPath
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:256)
com.ichi2.anki.tests.libanki.ImportTest > testDupeIgnore[test(AVD) - 4.1.2] FAILED 
	java.lang.NoSuchMethodError: java.io.File.toPath
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:256)
```

**Comment by mikehardy** [comment]
Go back in time on the dependency, zip64 worked on it starting at 1.3 and it looks like they didn't bump JVM reqs until much later http://commons.apache.org/proper/commons-compress/zip.html / https://commons.apache.org/proper/commons-compress/changes-report.html

**Comment by mikehardy** [comment]
commons compress 1.12 should do it, File.toPath is "since 1.7" on the upstream (non-Google/android) Java documentation

**Comment by david-allison-1** [comment]
Already on it,

**Timing**

 Spoonfed Chinese import on my Android 9 before the change

```
3m28:
2020-06-12 00:13:58.789 13682-13682/com.ichi2.anki E/ImportDialog: Start Import - New
2020-06-12 00:17:26.784 13682-13682/com.ichi2.anki E/DeckPicker: End Import - New

3m27
2020-06-12 00:19:08.498 13682-13682/com.ichi2.anki E/ImportDialog: Start Import - New
2020-06-12 00:22:35.181 13682-13682/com.ichi2.anki E/DeckPicker: End Import - New
```

**Comment by david-allison-1** [comment]
I'll stick 1.12 in now, it's faster testing via travis than on my local

**Comment by david-allison-1** [comment]
Works on my travis, handles a large file on both API 24 and 27 emulators

File: AnkiDroid/build.gradle [hunk 1]
```diff
@@ -144,6 +144,10 @@ dependencies {
     implementation 'com.getbase:floatingactionbutton:1.10.1'
     implementation 'org.bitbucket.cowwoc:diff-match-patch:1.2'
     implementation "androidx.multidex:multidex:2.0.1"
+    // #6419  - API 27 (& maybe others) could not perform new ZipFile() on a 2GB+ apkg
+    // noinspection GradleDependency - needs 1.12 as later versions use `File.toPath`
```
Comment (mikehardy) [inline AnkiDroid/build.gradle:148]:
```suggestion
    // noinspection GradleDependency - pinned at 1.12 until API21 minSdkVersion (File.toPath usage)
```

This makes it so it will be searched during minSdkVersion bumps, we (I?) always search for 'APINN' usage

**Comment by mikehardy** [comment]
I will pick this to release-2.11 branch 1-2 days after it soaks in alpha but I will let it sit beta in there for a bit, people can opt in.

File: AnkiDroid/build.gradle (hunk 1 above)
Comment (mikehardy) [reply AnkiDroid/build.gradle]: I literally thought of this one as I was falling asleep last night, which is a sure sign of mental illness. But I remembered it! Need to do another round of APINN searches, but testing revealed this needs to stay pinned until API26
